### ISSUE TITLE
Xenguest and qemu-dm wrapper alternatives gone

### ISSUE THREAD

**Issue by andreslagarcavilla** [xapi-project/xen-api#1364]
Installed xenerver-core on top of vanilla CentOS 6.4 and I can verify that specifying alternative xenguest and qemu-dm values in the platform field of a VM is moot.

This functionality was introduced in https://github.com/djs55/xen-api/commit/63d41a86fbbda3a384f41f97567222d4e0afd013

I believe the problem might be that xenopsd-xenlight just doesn't care about xenguest (I tried a suspend).

Also, I don't think /opt/xensource remains the right place to install alternatives. Any docs about that?

Thanks

**Comment by simonjbeaumont** [comment]
@andreslagarcavilla 

This is actually functionality in https://github.com/xapi-project/xenopsd now. It is still possible to specify an alternative to use by adding it to the platform field of the VM[1]

[1]: https://github.com/xapi-project/xenopsd/blob/6a56a0b/xc/xenops_server_xen.ml#L45-L58

This relies on them being available in the configurable `Xc_path.alternatives` directory which on a vanilla install on CentOS should default to `/usr/lib/xapi/alternatives/`[2].

[2]: https://github.com/xapi-project/xenopsd/blob/6a56a0b/xc/xc_path.ml#L28

This can be overriden in `/etc/xenopsd.conf` by setting the `alternatives=/path/to/dir/`[3]

[3]: https://github.com/xapi-project/xenopsd/blob/6a56a0b/xc/xc_path.ml#L45

(All references taken from the current `master` of Xenopsd: https://github.com/xapi-project/xenopsd/blob/6a56a0b)

However, as you say, this is only relevant for the `libxc` classic Xenopsd backend and not the Xenlight backend.

Hope this answers your question.
