### ISSUE TITLE
XenAPI.Failure: ['BOOTLOADER_FAILED', 'OpaqueRef:eeb23845-bac1-95b8-0a51-3994847e9906', 'UNSUPPORTED_INSTALL_METHOD\nother-config:install-repository was not set to an appropriate value, and this is required for the selected distribution type.\n\n']

### ISSUE THREAD

**Issue by mooperd** [xapi-project/xen-api#1597]
Hello,

I am attempting to install new virtual machines using scripts/examples/python/install.py but I am hitting the following error. Could I have some guidance on debugging this please?

Thanks,

Andrew

['BOOTLOADER_FAILED', 'OpaqueRef:eeb23845-bac1-95b8-0a51-3994847e9906', 'UNSUPPORTED_INSTALL_METHOD\nother-config:install-repository was not set to an appropriate value, and this is required for the selected distribution type.\n\n']
Traceback (most recent call last):
  File "./install.py", line 134, in <module>
    main(session)
  File "./install.py", line 89, in main
    session.xenapi.VM.start(vm, False, True)
  File "/root/xen-api/scripts/examples/python/XenAPI.py", line 245, in **call**
    return self.__send(self.__name, args)
  File "/root/xen-api/scripts/examples/python/XenAPI.py", line 149, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/root/xen-api/scripts/examples/python/XenAPI.py", line 219, in _parse_result
    raise Failure(result['ErrorDescription'])
XenAPI.Failure: ['BOOTLOADER_FAILED', 'OpaqueRef:eeb23845-bac1-95b8-0a51-3994847e9906', 'UNSUPPORTED_INSTALL_METHOD\nother-config:install-repository was not set to an appropriate value, and this is required for the selected distribution type.\n\n']

**Comment by mseri** [comment]
Closing as there are no followup since 2014.
