### ISSUE TITLE
We should distribute the database

### ISSUE THREAD

**Issue by djs55** [xapi-project/xen-api#2017]
If we adopt the design from https://github.com/xapi-project/xen-api/tree/master/doc/futures/distributed-database

Then we should
- improve scalability
- allow hosts to act independently (aka "pools of one")
- prevent races over database records by parallel Tasks

**Comment by simonjbeaumont** [comment]
I agree @djs55 ;) Since we have a design for that now which you have linked I'll close this issue since it's just a place-holder for work to be scheduled.
