### ISSUE TITLE
xe vbd-create doesn't understand type=floppy

### ISSUE THREAD

**Issue by chengsun** [xapi-project/xen-api#2073]
It looks like I missed a few spots with my floppy patches.

**Comment by djs55** [comment]
Fair enough. To be honest we may wish to postpone fixing this until the PV
tools bug has been fixed...

On Wed, Jan 7, 2015 at 6:00 PM, Cheng Sun <notifications@github.com> wrote:

> It looks like I missed a few spots with my floppy patches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/xen-api/issues/2073>.
>



-- 
Dave Scott

**Comment by gaborigloi** [comment]
This is still the case:
```
[root@dt14 ~]# xe vbd-create type=floppy vm-uuid=4383f051-cc9e-48d5-99e9-8fa2e979e2d0 device=/dev/sdb
Error: Unknown type: floppy (should be "cd" or "disk"
```
However, floppy is an actual `VBD` type: https://xapi-project.github.io/xen-api/classes/vbd.html

**Comment by lippirk** [comment]
this got fixed: https://github.com/xapi-project/xen-api/pull/4002/files
