### ISSUE TITLE
xen api connection refused

### ISSUE THREAD

**Issue by raidxx** [xapi-project/xen-api#2199]
I got connection refused error after installing xcp-xapi and starting the service.
I'm using Ubuntu 14.04.2 LTS with Xen hypervisor 4.4.

I'm following up the official tutorial => https://help.ubuntu.com/community/Xen
The Log file saying that xenctrl.error operation not permitted

**Comment by gaborigloi** [comment]
Closing as the `xcp-xapi` package from the tutorial was for Ubuntu Precise, which isn't supported any more (and sadly there isn't any xapi package for supported versions of Ubuntu).
