### ISSUE TITLE
Issues with JSON-RPC interface

### ISSUE THREAD

**Issue by julien-f** [xapi-project/xen-api#2265]
Hi, I am the lead dev of [Xen Orchestra](/vatesfr/xo) and we are investigating the use of JSON-RPC to talk to XAPI in Xen Server Dundee.

We are using our [xen-api](/julien-f/js-xen-api) Node module to talk to XAPI which uses the [JSON-RPC 2](https://github.com/julien-f/js-json-rpc-protocol) implementation [json-rpc-protocol](/julien-f/js-json-rpc-protocol).
## String identifier in request

A request identifier can be either a string or a number. ([source](http://www.jsonrpc.org/specification#request_object))

Currently, the following error is returned when a request identifier is a string:

``` html
<html>
<body>
    <h1>HTTP 500 internal server error</h1>
    An unexpected error occurred; please wait a while and try again. If the problem persists, please contact your support representative.
    <h1> Additional information </h1>
    Jsonrpc.Malformed_method_request(&quot;{\&quot;jsonrpc\&quot;:\&quot;2.0\&quot;,\&quot;method\&quot;:\&quot;session.login_with_password\&quot;,\&quot;params\&quot;:[\&quot;root\&quot;,\&quot;qwerty\&quot;],\&quot;id\&quot;:\&quot;foo bar\&quot;}&quot;)
</body>
</html>
```
## Missing `jsonrpc` field in response

A response MUST have `jsonrpc` field equals to `'2.0'`. ([source](http://www.jsonrpc.org/specification#response_object))
## Incorrect `result` field in error response

The `result` field of a response MUST NOT exist if there is an error. ([source](http://www.jsonrpc.org/specification#response_object))

**Comment by jonludlam** [comment]
Xapi in Dundee currently uses the 'ocaml-rpc' library [1], which only
implements jsonrpc 1.0 - we might look to upgrade this at some point,
depending on how big a change 2.0 is (on the surface it doesn't seem
too bad [2]). If you wanted to hurry the change along, pull requests
to ocaml-rpc would, I'm sure, be warmly received :-)

[1] https://github.com/mirage/ocaml-rpc
[2] http://www.simple-is-better.org/rpc/#differences-between-1-0-and-2-0

**Comment by julien-f** [comment]
I created an issue on their side (mirage/ocaml-rpc#32) but I think the best approach for me is to support JSON-RPC 1 on my side.

**Comment by julien-f** [comment]
Done.

But I am wondering what would be the best way to negotiate the protocol?
Maybe I should try with JSON-RPC and fall back to XML-RPC+JSON if I get a 500 error…

**Comment by mseri** [comment]
Closing this as `ocaml-rpc` has been supporting json-rpc v2 for some time now..
