### ISSUE TITLE
Error 500 with JSON embedded in XML-RPC with XS 6.2 

### ISSUE THREAD

**Issue by julien-f** [xapi-project/xen-api#2337]
A recent patch for Xen Server 6.2 (XS62ESP 1011, 1013, 1014 or 1025) introduce a bug with `event.from` on large pools: instead of a XML-RPC response I get a HTTP 500 (Server Error).

See julien-f/js-xen-api#2.

**Comment by olivierlambert** [comment]
Added comment: https://github.com/julien-f/js-xen-api/issues/2#issuecomment-159403398

More details probably to come (XenServer logs)

**Comment by mseri** [comment]
Is this still an issue on XenServer 7+?

**Comment by olivierlambert** [comment]
We don't have enough large pool to test that behavior. We switched to pure JSON in recent XS versions anyway.

**Comment by mseri** [comment]
Thanks.

I am closing it for now, will reopen if the issue reappear
