### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by emmagordon** [xapi-project/xen-api#2777]
Hi - I was just browsing through the documentation to get an overview of the project. The following links are broken and should be removed/fixed as appropriate:
1. The 'Internals of xapi' diagram on the [architecture](https://github.com/xapi-project/xen-api/blob/master/doc/architecture/README.md) page.
2. The 'Features' and 'Walk-throughs' links in the 'Contents' section of the doc's[ README](https://github.com/xapi-project/xen-api/blob/master/doc/README.md) file.

Thanks!

**Comment by jonludlam** [comment]
Hi @emmagordon - thanks for the report! Most of the documentation here has been superseded by https://xapi-project.github.io/ - so the xapi architecture page is now: [here](http://xapi-project.github.io/xapi/architecture.html), the features are on the sidebar of that page and there's only one [walkthrough](http://xapi-project.github.io/xenopsd/walkthroughs/VM.start.html) under the `xenopsd` page.

We should probably remove this vestigial doc dir in favour of pointing at the main xapi-project page instead.

**Comment by gaborigloi** [comment]
Thanks for reporting the issue, I'm closing it as commit c47a31930ecf66b1e6a737a8fa1544d5ecb666fc removed this obsolete `/doc/` directory.
