### ISSUE TITLE
XenServer 7 Direct Insepect API

### ISSUE THREAD

**Issue by deliciousdish** [xapi-project/xen-api#2786]
Hi, i was just reading the wiki of xenserver 7. Can you tell me where the code of the Direct Inspect API sets is? Is it in this repository or in others ? 
Thanks !

**Comment by mseri** [comment]
I don't know where the API are exactly but they are not part of xapi, you should probably look into xen: https://wiki.xen.org/wiki/Virtual_Machine_Introspection
