### ISSUE TITLE
Python 3 and XenServer 7 Support?

### ISSUE THREAD

**Issue by patran** [xapi-project/xen-api#2879]
Is there a python 3 version? I don't think the current version 1.2 works with Python 3. I ran into xmlrpclib and httplib issues.

**Comment by mseri** [comment]
There is not yet a python3 Xapi library, however you can use the standard python3 xmlrpc client and call the api with that. I am going to post an example here tomorrow

**Comment by patran** [comment]
This one works with Python 3.

https://github.com/saruba/xen-api

**Comment by mseri** [comment]
Interesting, thanks.
You can also use python's xmlrpc, provided that you carry a reference to the `session`:
```
hosturl = "HOST_URL_GOES_HERE"
user = "USER_NAME_GOES_HERE"
password = "PASSWORD_NAME_GOES_HERE"
import xmlrpc.client
client = xmlrpc.client.ServerProxy('http://%s' % hosturl)
session_ref = client.session.login_with_password(user, password)
hosts = client.VM.get_all_records(session_ref)
print(hosts['Value])
client.session.logout(session_ref)
```

**Comment by mseri** [comment]
The new sdk supports python 3 as well as of today https://github.com/xapi-project/xen-api/pull/3111
