### ISSUE TITLE
XenAPI.py Licencing Question

### ISSUE THREAD

**Issue by TBSliver** [xapi-project/xen-api#3061]
In digging for the original licence for a nagios/icinga check plugin, I have found that there are two files that have different licences but are mostly the same in terms of contents. These are:

* https://github.com/xapi-project/xen-api/blob/master/ocaml/idl/binding_sanity_checks/tutorial_examples/XenAPI.py
* https://github.com/xapi-project/xen-api/blob/master/scripts/examples/python/XenAPI.py

The second of those files had its licence changed to BSD, the former carries the LGPL v2.1 licence - which is the same as the licence at the base of this repository.

As BSD (2 clause) and LGPL are GPL compatible licences (https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility) I have a feeling this issue is not a massive one, but thought that you should be aware of it, especially for code which is as prevalent in various places as the XenAPI.py file is.

my full breakdown can be found in this commit message, including the other file which is a derivative of another file in this repository - if I have made a mistake with the licencing, please let me know!

* https://github.com/TBSliver/Icinga-Plugin-XenServer/commit/adaff31dce20d5c7e53415bdd46f0a1191d13d44

**Comment by mseri** [comment]
Thanks for pointing this out.

We are going to remove the `binding_sanity_check` folder (that remained there for historical reasons only). The licence is the BSD used in the script in `examples`.

You might want to update the python plugin using the new python3 compatible one just merged: https://github.com/xapi-project/xen-api/pull/3111
