### ISSUE TITLE
Standalone VM operations service/API

### ISSUE THREAD

**Issue by SecureStack** [xapi-project/xen-api#3068]
Is it possible to run standalone **xenopsd** to perform VM lifecycle operations? I was able to install xenopsd, but it installs as a library. Any pointers on how to run and interact with a standalone xenopsd would be very helpful.

**Comment by mseri** [comment]
Closing it as it should be discussed in the xapi-project/xenopsd issue section.

This said, you need to use the `xenopsd-xc` binary generated running `make`, but probably you also need to provide a configuration (an example .conf file is in the repository).
