### ISSUE TITLE
XenAPI.py pip3 question

### ISSUE THREAD

**Issue by horsebattery** [xapi-project/xen-api#3157]
Is there any way to include python3 version of XenAPI in my project requirements, so that other people can get it by using pip, or the only option for now is to include XenAPI.py file in project itself? Thanks in advance!

**Comment by Keleir** [comment]
The same needs. I have to try use `futurize` the XenAPI.py (py2 version) into py3 version, but some fatal error occurs. Any other way ? Thanks.

**Comment by mseri** [comment]
The current version (github repository) of XenAPI is python 2 and 3 compatible and is in the process of being packaged. After that is done there is no plan to upload it on pypi at the moment. As happened to other languages xapi sdk, at that point you are free to publish it on pypi for ease of use with pip. 

Unfortunately the current pip library cannot be updated: we asked multiple times the pypi maintainer to unlock it for upload but we never got an answer.

**Comment by mseri** [comment]
We are in the process of repackaging the python scripts and examples, at that point we are going to copy the python api to an external repository and you will be able to install it with `pip install link/to/github/tarball`

**Comment by salotz** [comment]
Thats a shame about the PyPI repo. Has the situation changed? And is there an independent repository somewhere. I was basically going to do the same thing for my own purposes.

**Comment by psafont** [comment]
A python-3-compatible version is now available on https://pypi.org/project/XenAPI/2.14/
