### ISSUE TITLE
XAPI database and xensource-inventory vulnerables to power failures (non-atomic writes?)

### ISSUE THREAD

**Issue by stormi** [xapi-project/xen-api#4319]
I had reported an [XSO](https://bugs.xenserver.org/browse/XSO-969) 15 months ago but I think a github issue will probably be more appropriate.

From time to time, a user has a power failure on a host, which apparently happens in the middle of a write operation to an important file such as `/etc/xensource-inventory` or the XAPI database itself. The file is then corrupted and the host unusable until this is fixed - when they have a backup that they can restore.

I've seen it happen once on `xensource-inventory` (file was truncated after the first 4 lines) and met broken XAPI databases several times.

I believe that this could be avoided if the write operations were atomic. I don't know what the best solution is. The first that comes to mind is writing to a new file, rename existing file to .bak, rename new file, delete .bak, but it's probably a naïve take on the issue.

**Comment by edwintorok** [comment]
We have a write atomic helper function that writes to a tempfile in the same dir, fsyncs it, renames it (and probably fsyncs the parent dir), and should probably be used when changing xensource-inventory (it should be a rare operation).

That wouldn't help with the XAPI DB though which is all in memory. You have to enable the redo-log or HA for that, by default changes to the XAPI database are not durable.

**Comment by stormi** [comment]
About XAPI, couldn't the writes to state.db be made atomic too? Users sometimes end-up with files that are broken to the point that the XAPI DB can't be initialized anymore when XAPI starts.

Good to know about the file being written only on clean shutdowns and toolstack restarts. I thought that would happen more regularly, as a safety measure.

**Comment by robhoes** [comment]
>Good to know about the file being written only on clean shutdowns and toolstack restarts. I thought that would happen more regularly, as a safety measure.

It does, every couple of minutes (as well as when xapi is stopped).

**Comment by stormi** [comment]
So I suppose that's when a power failure is dangerous and what causes the issues we see from time to time? So back to the initial question, is there a way to make this write atomic?

**Comment by robhoes** [comment]
It seems that we do: https://github.com/xapi-project/xen-api/blob/master/ocaml/database/backend_xml.ml#L54

The database file should not get corrupted because of a power cut, but would be out of date by up to a couple of minutes, unless the redo-log is enabled (usually as part of HA).

**Comment by psafont** [comment]
Note that the function used there to atomically write files was rewritten for 8.2 to ensure the file is completely written to disk or not at all: https://github.com/xapi-project/stdext/pull/43

**Comment by stormi** [comment]
Thanks. I don't think I have had reports of corrupted state.db in 8.2 at the moment. I'll try to keep all that information in mind in case it happens in the future. 

Is `xensource-inventory` also written atomically yet?

**Comment by psafont** [comment]
> Is `xensource-inventory` also written atomically yet?

I believe so, It's written in https://github.com/xapi-project/xcp-inventory/blob/master/lib/inventory.ml#L76 and https://github.com/xapi-project/xcp-inventory/blob/master/lib/inventory.ml#L108
The function `write_string_to_file` ultimately uses `atomic_write_to_file`: https://github.com/xapi-project/stdext/blob/master/lib/xapi-stdext-unix/unixext.ml#L182-L184

**Comment by stormi** [comment]
Thanks again. Then everything seems to be right, and the previously seen issues were possibly due to the now fixed issues in `atomic_write_to_file`. Let's consider the case closed for now then!

Best regards.
