### ISSUE TITLE
Proposal to move IRC channel to oftc.net

### ISSUE THREAD

**Issue by gwd** [xapi-project/xen-api#4424]
This message is because the xapi project is listed as having an IRC channel on `freenode.net` (see https://xenproject.org/help/irc/ )

There's been a situation developing on freenode for some time that came to a head last week.  Since that time, the new operators of freenode have begun seizing control of any channel whose topic mentions moving to a new server.  Furthermore, they have been using the number of people logged into freenode as evidence that the community supports their actions.

In response to this, the main hypervisor project has decided to move to `oftc.net` effective immediately, and a number of us have deleted our freenode accounts ( https://lists.xenproject.org/archives/html/xen-devel/2021-05/msg01057.html ).

If you're still using the IRC channel listed in that page, please consider following suit.  If you're not using the IRC channel, let me know so I can delete references to it.

**Comment by edwintorok** [comment]
I've never used that IRC channel, maybe @psafont would know if anyone uses it.

**Comment by psafont** [comment]
I don't use it, @olivierlambert do you mind moving the channel to the otfc network?

**Comment by robhoes** [comment]
Our team used it in the past, but not for at least five years. I would suggest deleting the references to it from xenproject.org.

**Comment by olivierlambert** [comment]
Could we keep something where we could have access to XAPI devs from outside Citrix? I don't think it will cost a lot to create a chan there. We could do the active watch if needed. Benjamin could be the main contact point.

**Comment by robhoes** [comment]
The point is, none of the active xapi devs have been on that Freenode channel (or even knew about it :) )...

**Comment by gwd** [comment]
Right; so we could certainly remove xapi-devel from the xenproject.org webpage.  But I think @olivierlambert is requesting that you make a channel on OFTC and have some devs join it instead. :-)

**Comment by robhoes** [comment]
I know :) We are discussing it.

**Comment by olivierlambert** [comment]
That might be a good opportunity to have more fluid exchanges since now XAPI is an upstream for multiple downstream distros.

**Comment by gwd** [comment]
I guess the other option would be to have some of the xapi people lurk on xcp-ng-dev (which was recently created on OFTC).

**Comment by gwd** [comment]
Unless I hear otherwise by EOD today, I'll delete the reference from the xenproject.org IRC page.  We can always add it back in if you guys decide to start using it.
