### ISSUE TITLE
The value defined in xapi.conf's `web-dir` is ignored

### ISSUE THREAD

**Issue by stormi** [xapi-project/xen-api#4512]
(tests done on Stockholm release)

I have tried to set the `web-dir` parameter, that defaults to `/opt/xensource/www`, in `xapi.conf`. I thought that a different value would make XAPI serve files from a different directory (e.g. `/var/xapi_http_root`).

However, whatever the value I set, HTTP requests on port 443 still provide files from `/opt/xensource/www`.

Is it the expected behaviour or is there a bug?

**Comment by psafont** [comment]
There's a single use of web-dir, that's for the `get_root` http handler, which is defined as
```
  ("get_root", (Get, "/", false, [], _R_READ_ONLY, []));
```

While the URIs are usually defined in the Constants modules instead of being harcoded, it doesn't look incorrect as they all start with a slash.

I don't see how it could go wrong, have you tried restarting the xapi daemon to reload xapi.conf?

**Comment by stormi** [comment]
Yes, I restarted the toolstack and HTTPS requests on port 443 still provide files from `/opt/xensource/www` as if I had changed nothing. The value I define in xapi.conf is used at some point, because if I define it as a relative path on purpose (like `../thiswillfail`), then XAPI fails to start with this error:
```
Sep  3 11:51:09 r620-q6 xapi: [error||0 ||xapi] Cannot access ../thiswillfail
Sep  3 11:51:09 r620-q6 xapi: [error||0 ||xapi] Please either add to /etc/xapi.conf
Sep  3 11:51:09 r620-q6 xapi: [error||0 ||xapi]   web-dir=<Directory to export fileserver>
Sep  3 11:51:09 r620-q6 xapi: [error||0 ||xapi] or add a command-line argument
Sep  3 11:51:09 r620-q6 xapi: [error||0 ||xapi]   /opt/xensource/bin/xapi -nowatchdog -writereadyfile /var/run/xapi_startup.cookie -writeinitcomplete /var/run/xapi_init_complete.cookie --web-dir=<Directory to export fileserver>
```

**Comment by stormi** [comment]
I added debug traces in `send_dir`, and the value of `dir` that is passed to it is always `/opt/xensource/www`.

**Comment by stormi** [comment]
So I made this change to `ocaml/xapi/xapi.ml`

```
Index: xapi-1.249.10/ocaml/xapi/xapi.ml
===================================================================
--- xapi-1.249.10/ocaml/xapi/xapi.ml
+++ xapi-1.249.10/ocaml/xapi/xapi.ml    2021-09-09 17:19:55.670281335 +0200
@@ -727,7 +727,7 @@
   ; ("get_export_raw_vdi", Http_svr.FdIO Export_raw_vdi.handler)
   ; ("connect_console", Http_svr.FdIO (Console.handler Console.real_proxy))
   ; ("connect_console_ws", Http_svr.FdIO (Console.handler Console.ws_proxy))
-  ; ("get_root", Http_svr.BufIO (Fileserver.send_file "/" !Xapi_globs.web_dir))
+  ; ("get_root", Http_svr.BufIO (Fileserver.send_file "/" "/srv/wwwroot"))
   ; ("post_cli", Http_svr.BufIO Xapi_cli.handler)
   ; ("get_host_backup", Http_svr.FdIO Xapi_host_backup.host_backup_handler)
   ; ("put_host_restore", Http_svr.FdIO Xapi_host_backup.host_restore_handler)
   ```
   
Our hypothesis is that ` !Xapi_globs.web_dir` is evaluated (at XAPI startup? At build?) before `xapi.conf` has been read.

**Comment by robhoes** [comment]
I think the problem is that `common_http_handlers` in xapi.ml, which has the above code, is not a function but a value that is immediately evaluated when the module loads. That is immediately when the program starts, and before the function calls are made to read the conf file.

You should be able to fix that by making it a function. Add a `()`:

    let common_http_handlers () =

...and update the caller in `server_init`.

**Comment by benjamreis** [comment]
Thanks for the answer! We'll give that a try and report here :)

**Comment by stormi** [comment]
It worked. I'm creating a PR.
