### ISSUE TITLE
[Feature proposal] Ignore some VDIs when snapshoting a VM

### ISSUE THREAD

**Issue by benjamreis** [xapi-project/xen-api#4551]
Hello,

Here's a feature request we received from XO team that we think could be of interest to you as well:

Having the ability to exclude some VDIs when snapshoting a VM to save time & space.
Some example:
- users using a raw disk for having a big storage (if you can exclude it, you'll be able to do a VM.snapshot, you can't right now)
- users with non-relevant data to save on large disks (binaries etc.), so they can explicitly NOT snapshotting a disk

What do you think?

**Comment by edwintorok** [comment]
if you don't want to snapshot a disk, make it a raw VDI, you'll gain some performance advantages as well. The default is a snapshottable vhd or qcow2 internally, which has some overhead solely for the purpose of making snapshotting (and various forms of migration) possible.

Obviously that VM will then as a whole become unsnapshottable (e.g. what if you put your DB on the unsnapshottable disk, but by reverting to a snapshot you also revert to an older version of your DB server which now can't read your files?)
If you know what you are doing there could be a new unsafe_snapshot API that ignores the raw disks (and is very explicit in its name that it is unsafe).

There might be some implications about using raw disk (e.g. you might loose the ability to do storage migration)
