### ISSUE TITLE
DUPLICATE_VM error, impossible to find the cause

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xen-api#4567]
Hello!

We got an interesting case of someone having issues to migrate a VM to another pool, failing with `xe` with:
```
Cannot restore this VM because it would create a duplicate
```
Obviously, same result with Xen Orchestra, it's not a XAPI client issue, but clearly something on XAPI side itself. However, despite trying to find duplicate data between VMs, we couldn't find anything (except `mac_seed` but I don't think that's the culprit).

More details are provided here: https://xcp-ng.org/forum/topic/5151/migrating-vm-fails-with-duplicate_vm-error-part2

**Comment by olivierlambert** [comment]
So after some tests, we confirm that this error is display if you have the same `mac_seed` between 2 VMs.

Is that expected? To me, a MAC seed is just… a seed.

**Comment by undu** [comment]
The VIF mac's are generated in a deterministic manner from the mac seed and the device number, this is why the seeds are forced to be unique

**Comment by psafont** [comment]
I think so, reopen if you think it needs more fixing (I don't think this has been marked for backporting)
