### ISSUE TITLE
Basic authentication will fail if password contains ':'

### ISSUE THREAD

**Issue by cheese** [xapi-project/xen-api#4593]
https://github.com/xapi-project/xen-api/blob/fa0965b4d7a40e4726d5b784e37fc368cdf550f4/ocaml/libs/http-svr/http.ml#L217

If password contains `:`, it will fail to match case `[ username; password ]`.

**Comment by lindig** [comment]
Indeed:

```
utop # Astring.String.cuts ~sep:":" "one:two:three";;
- : string list = ["one"; "two"; "three"]
```

**Comment by psafont** [comment]
`Astring.String.cut` provides an adecuate resultin this case, although careful consideration is needed for all cases:
```
# Astring.String.cut ~sep:":" "one:two:three";;
- : (string * string) option = Some ("one", "two:three")
```

**Comment by edwintorok** [comment]
We could also use the parsers from `cohttp` (even if we don't yet use cohttp itself for parsing http):
```
Cohttp.Auth.credential_of_string "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==";;
- : Cohttp.Auth.credential = `Basic ("Aladdin", "open sesame")
```
