### ISSUE TITLE
Use ipv6_allowed with ranges in VIF object

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xen-api#4694]
Hello there,

We have a user request to use `ipv6_allowed` field with IP range or CIDR notation, instead of entering an insane number of IPv6 addresses. For example, if you have a `/64`, it means 2⁶⁴ possible addresses. But it's still possible to give a /64 to someone, since there's plenty of IPv6 available.

If I understand correctly, XAPI (`xenopsd` in fact?) will use `ebtables` to create rules. Could we tell it to allow a range instead of individual IPv6?

edit: after taking a closer look on it, it seems that allowed IP is in fact using Open Flow rules of OVS (since by default we are in OVS mode and not Linux bridge). So the question is about creating an Open Flow rule with a CIDR notation.

**Comment by olivierlambert** [comment]
So if I understand it correctly, it's happening here: https://github.com/xapi-project/xen-api/blob/dfaf3839c9d05a9bff889a7d8de55fef8786d649/ocaml/xenopsd/scripts/setup-vif-rules#L263-L265

What matters is `ipv6_src` and it seems that OVS does support CIDR block notation [1] (thanks @AtaxyaNetwork for finding it within the doc):

```
       ipv6_src=ipv6[/netmask]
       ipv6_dst=ipv6[/netmask]
              When  dl_type  is  0x86dd (possibly via shorthand, e.g., ipv6 or
              tcp6), matches IPv6 source (or destination) address ipv6,  which
              may  be  specified as defined in RFC 2373.  The preferred format
              is x:x:x:x:x:x:x:x, where x are the hexadecimal  values  of  the
              eight 16-bit pieces of the address.  A single instance of :: may
              be used to indicate multiple groups of 16-bits  of  zeros.   The
              optional  netmask  allows restricting a match to an IPv6 address
              prefix.  A  netmask  is  specified  as  an  IPv6  address  (e.g.
              2001:db8:3c4d:1::/ffff:ffff:ffff:ffff::)  or  a CIDR block (e.g.
              2001:db8:3c4d:1::/64).  Open vSwitch 1.8 and later support arbi‐
              trary  masks; earlier versions support only CIDR masks, that is,
              CIDR block and  IPv6  addresses  that  are  equivalent  to  CIDR
              blocks.
```

So in theory, this should work out-of-the-box for OVS. Now let's check about XAPI itself.


[1]: https://www.openvswitch.org/support/dist-docs-2.5/ovs-ofctl.8.txt

**Comment by olivierlambert** [comment]
The result on `xe` is pretty straightforward:

```
# xe vif-param-set ipv6-allowed="2a01:xxxx:xxxx:xxxx::/64" uuid=xxxx
A required parameter contained an invalid IP address
```

I suppose IP are parsed on XAPI's side anyway, so now let's check if we can add the rule directly in OVS, and validate it. If yes, it means it's just a matter of accepting the CIDR notation in XAPI's input check.

**Comment by psafont** [comment]
> If yes, it means it's just a matter of accepting the CIDR notation in XAPI's input check.

It's worth a try, the ipaddr ocaml library supports CIDR notations, so it should be easy to do the validation.

**Comment by olivierlambert** [comment]
So after various investigations, here is my conclusion: **it works when CIDR rules are added manually in OVS** :partying_face: 

For reference, here is a real example to authorize ICMP6 requests on the right port for the whole /112:

```
ovs-ofctl add-flow xenbr4 in_port=20,priority=8000,dl_src=32:e9:86:c7:ee:31,icmp6,ipv6_src=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:fec7::/112,icmp_type=135,nd_sll=32:e9:86:c7:ee:31,idle_timeout=0,action=normal
ovs-ofctl add-flow xenbr4 in_port=20,priority=8000,dl_src=32:e9:86:c7:ee:31,icmp6,ipv6_src=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:fec7::/112,icmp_type=136,nd_target=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:fec7::/112,idle_timeout=0,action=normal
ovs-ofctl add-flow xenbr4 in_port=20,priority=5000,dl_src=32:e9:86:c7:ee:31,ipv6_src=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:fec7::/112,icmp6,action=normal
```

I did a ping test on my side, and only the IPv6 added in the /112 network are authorized and answering the request, anything else outside that /112 (as planned) is blocked.

The next step is to authorize this in XAPI, and just getting xenopsd pass the whole thing directly to OVS, I don't see any blocker to that.

**Comment by olivierlambert** [comment]
Obviously, feedback is welcome if I overlooked something during my tests :)

**Comment by olivierlambert** [comment]
Fixed by https://github.com/xapi-project/xen-api/pull/4871
