### ISSUE TITLE
setuptools warnings

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [xapi-project/xen-api#4715]
```
 * QA Notice: setuptools warnings detected:
 * 
 * 	Usage of dash-separated 'long-description-content-type' will not be supported in future versions. Please use the underscore name 'long_description_content_type' instead
```

**Comment by psafont** [comment]
I believe this doesn't happen anymore on latest commit, could you retry running it and confirming?

**Comment by Alessandro-Barbieri** [comment]
I still see it here https://github.com/xapi-project/xen-api/blob/6884a2a62028910df1b90223664d9e5319dbae27/scripts/examples/python/setup.cfg#L5
