### ISSUE TITLE
redirect http to https in XAPI when you call the `http(s)://<ip_server>`

### ISSUE THREAD

**Issue by benjamreis** [xapi-project/xen-api#4856]
Hi!

As said in the title, we'd like to redirect people accessing the homepage of host through http to https.
Are there, from the go, any problem with that that we're not aware of?

Thanks

**Comment by robhoes** [comment]
Hi, I'm fine with that. However, we have now added an option to close port 80 completely, as some people prefer that for security reason. Port 80 is still open by default, but when closed, then the redirection won't work anymore, as nothing will be listening on port 80.
