### ISSUE TITLE
Guest SecureBoot, existing VMs, and user experience

### ISSUE THREAD

**Issue by stormi** [xapi-project/xen-api#4888]
This topic may concern XAPI, varstored, and UI (xe, xenadmin, Xen Orchestra...).

Context: `varstored` only ever installs UEFI certificates to a VM's NVRAM store the first time the VM start. After this, the only way I know to install the default certificates to it is by manually running `varstore-sb-state {VM-UUID} user`.

For a user, this is confusing **when they attempt to enable Secure Boot on a VM which was already booted but doesn't have any certificates yet**: the VM boots, XAPI says Secure Boot is enabled, but actually Secure Boot is silently disabled because from `varstored`'s point of view the VM is in setup mode (no certs), **even if this was not a user's conscious choice**.

In Citrix Hypervisor 8.2, this was probably not an issue:
* on UEFI hosts, there always were certificates before a VM was booted (except maybe for UEFI VMs created in 8.1, but UEFI support was experimental at the time so it was not a problem that users had to run `varstore-sb-state`).
* on legacy BIOS hosts, there was no guest Secure Boot support.

In XCP-ng 8.2, this was not an issue either because - despite hosts didn't have certificates until users would run `secureboot-certs install` at least once - `uefistored`'s behaviour differed from `varstored`'s: any VM that was booted and found without any certificates would automatically get new certificates from the host's certificates stored on disk. This was a convenient bug allowing to make SB work as soon as the host certificates were installed.

But in the next releases of both XenServer and XCP-ng, this becomes an issue:
* XenServer gets SB support on BIOS hosts too, but these may already have UEFI VMs.
* XCP-ng replaces uefistored with varstored.

To me, there are two issues, from the user perspective:
1. As a user, you enable Secure Boot in the VM's XAPI configuration, but this has no effect, because your VM was already started, in the past, on a host which had no certificates.
2. You may even not realize it had no effect, as you don't have any feedback when XAPI aks for SB to be enabled, but actually varstored disablesit due to setup mode (= missing certs). This was discussed with @rosslagerwall in https://github.com/xapi-project/varstored/issues/16 and a potential solution devised: add a parameter to tell varstored it should abort booting if XAPI was asking for SecureBoot but SecureBoot can't be enforced due to missing or broken certificates.

I'd ideally like us to address both issues, in a way which is acceptable for both XenServer and XCP-ng.

A few leads:
* For issue 2., implement the proposed solution. A flag for varstored, better feedback from varstored to XAPI at VM boot time, error handling in XAPI. If this is implemented, issue 1. becomes less important, thanks to the immediate failure.
* For issue 1., I'm not sure what the best solution is.
  * Ideally, enabling Secure Boot in XAPI should allow to really enable Secure Boot. 
    * Have XAPI automatically run `varstore-sb-state {VM-UUID} user` when someone switches Secure Boot to on? Then anyone who actually wants setup mode (probably rare, as a use case?) can manually run `varstore-sb-state {VM-UUID} setup`. Or create a new API call such as `enable_sb_user_mode`, which Xen Orchestra and XenCenter could use to put a VM in secure boot mode, and which would fail conveniently if for any reason certs are not available on disk?
    * As a component in this issue is that there is no way for either varstored or XAPI to know if a VM was put in setup mode on purpose or by accident (= started before there were certificates on host), let XAPI store this state (use mode/setup mode) and do the relevant `varstore-sb-state` calls when switching state? It would then become obvious even from XAPI's perspective that certificates are missing and XAPI could issue an error if you attempt to boot a VM which is supposed to be in user mode but actually has no certificates?
  * Otherwise, we should at least warn:
    * Delegate the detection of missing certs to user interfaces such as XenCenter and Xen Orchestra, when a user chooses to enable Secure Boot for a VM? This could be a small warning just next to the boot mode field: "/!\ certificates missing".

CCing @edwintorok @rosslagerwall @psafont

**Comment by kc284** [comment]
Regarding the last bullet point, there is already some work under way to improve XenCenter's behaviour in the next release.

**Comment by stormi** [comment]
> However I don't think it should've been currently possible to _enable_ secureboot on a VM without having host certs, if that is possible it sounds like a XAPI bug.
> Also XenCenter shouldn't have allowed that. And the default is secureboot auto which will then just got changed to secureboot off. Do you have a way to reproduce the "VM with secureboot enabled but without any certificates inside"?

I'm not aware of any checks before enabling Secure Boot for a VM through XAPI. Maybe there is in XenCenter. For what I know, Xen Orchestra doesn't check anything before someone toggles Secure Boot on.

![image](https://user-images.githubusercontent.com/451043/212702903-04d757a3-605e-4cdc-8661-3b1df8f97e5f.png)

Anyway, the issue we have is for any existing UEFI VM that users would want to enable Secure Boot for in the future, regardless of its prior status. Whether SB is enabled or not for a VM is only something that `varstored` will use to determine whether to try to enforce Secure Boot, but it has no effect on whether the UEFI certificates from the host are installed to the VM's NVRAM store or not. This all depends on what certs were available on disk on the host when the UEFI VM was booted the very first time. Afterwards, the NVRAM store remains untouched. So, on any existing UEFI VM first started on a host without SB certs (in XS world, any BIOS host, I believe?) will remain without certs, and enabling SB for it won't work until `varstore-sb-state UUID user` is called. That's why one of my suggestions is a XAPI call that bundles together enabling Secure Boot and installing the certs from the host.

**Comment by stormi** [comment]
The reason I opened this issue was to avoid a situation I thought was going to happen, where users may enable Secure Boot in XAPI, and see their VM boot, with Secure Boot actually silently disabled under the hood, due to the absence of certificates.

Such a situation is unlikely to happen. There will be VMs which don't have any KEK, db and dbx, but they won't boot if Secure Boot is enabled, so the risk of false sense of security I wanted to avoid will not happen.

What remains is only a usability issue, and I think you already handled it in XenCenter (or planned to): what to do when users want SecureBoot but their VM only has a PK, and not other UEFI certs (in XenServer, such VMs would have been created on Citrix Hypervisor 8.2 on a non-UEFI host, AFAICT). How to make them know that they need to run `varstore-sb-state <vm-uuid> user` to install the certificates that are on the host disk inside the VM's NVRAM, so that it becomes SecureBoot-capable.

Thus I'm closing this issue.

A enhancement that would be useful would be if XAPI would expose a simple way to query a VM's certificate store, so that clients can easily display useful information such as : "This VM is in setup mode", "Secure Boot is enabled, but certificates are missing. Here's how to install them...". In the current state, AFAIK, it's not impossible, but the client will need to fetch the whole .tar file containing the UEFI certificates.
