### ISSUE TITLE
`Field 'tags' is read-only.` when setting it via `xe vm-param-set tags`

### ISSUE THREAD

**Issue by gdelafond** [xapi-project/xen-api#5286]
Hello,

I try to set tags on a VM with `xe vm-param-set uuid=bbadf1e9-8da9-d347-2c60-8f4f5e725ae5 tags=test` but it says that the `Field 'tags' is read-only.`

The tags Field is a `SRW` field when listing it the `xe vm-param-list`:
```
# xe vm-param-list uuid=bbadf1e9-8da9-d347-2c60-8f4f5e725ae5 | grep tags
                                  tags (SRW):
```

Is it a bug of the XAPI? or did I make mistakes when using `xe vm-param-set tags`?

Thank you.

**Comment by robhoes** [comment]
You can use:

    xe vm-param-add uuid=... param-name=tags param-key=...

which sets individual values in the set. For some reason, the `tags` field does not have a "set all tags at once" option (some other set field do have this, with comma-separated lists).

**Comment by gdelafond** [comment]
@robhoes It works with `xe vm-param-add`. 
I did not think to look at another command as the error was `Field 'tags' is read-only`. The error should be something like `This is a set, use xe vm-param-add` I think.

Thank you!

> For some reason, the tags field does not have a "set all tags at once" option (some other set field do have this, with comma-separated lists).

:(
