### ISSUE TITLE
@ashwin9390: Complete CP-45974 (port examples folder to Python3): Specify Python >= 3.6

### ISSUE THREAD

**Issue by bernhardkaindl** [xapi-project/xen-api#5320]
@ashwin9390 : As part of #5292, this line should have been updated accordingly:

https://github.com/xapi-project/xen-api/blob/01dfc98b0bda437001bf2a27cd00759b66d0e916/scripts/examples/python/setup.cfg#L22

Now, it should state that Python >= 3.6 is required.

I would have assigned @ashwin9390 to this issue, but apparently I have not yet been added as a project member, so I can't assign and can't request changes to PRs that are required to be resolved for merging a PR.

**Comment by ashwin9390** [comment]
> @ashwin9390 : As part of #5292, this line should have been updated accordingly:
> 
> https://github.com/xapi-project/xen-api/blob/01dfc98b0bda437001bf2a27cd00759b66d0e916/scripts/examples/python/setup.cfg#L22
> 
> Now, it should state that Python >= 3.6 is required.
>  python_requires = >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4  which indicate greater than equal to  2.7 ,it does not include 3.0 to 3.4 ,anything less than 4 (version from 3.5 till latest not version 4 is included ) this python requires statement holds good here . 


> I would have assigned @ashwin9390 to this issue, but apparently I have not yet been added as a project member, so I can't assign and can't request changes to PRs that are required to be resolved for merging a PR.
