### ISSUE TITLE
Record yangtze schema version?

### ISSUE THREAD

**Issue by gthvn1** [xapi-project/xen-api#5393]
:wave: 
It is more a question than an issue to @robhoes about the commit that updates the API version and also updates yangtze schema version. I expected to see a version `774` for the new release and then a schema_minor_vsn set to `800`. I'm missing something I think :).
I'm not sure if it is the right place to ask so feel free to point me the right place.

Have a nice day,
Guillaume

**Comment by gthvn1** [comment]
I'm referring to [commit 7b6569](https://github.com/xapi-project/xen-api/commit/7b656911601f78f7137e4f8562a255746c0e3bbc)

**Comment by gthvn1** [comment]
It is an old one but I'm currently looking how xapi db versioning is working so that's why I'm asking ;)

**Comment by robhoes** [comment]
The `yangtze_release_schema_minor_vsn` is just a reference to schema version as it was for the Yangtze release. And `schema_minor_vsn` is the current schema version.

Yangtze was not a major version, but an update on Stockholm after which Stockholm itself was no longer updated. So we didn't need the gap in versions.

**Comment by gthvn1** [comment]
Ok got it. I thought Yangtze was a major version. Thx for the enlightenment :+1:
