### ISSUE TITLE
SMT discoverability: add thread_per_core info in host.cpu_info

### ISSUE THREAD

**Issue by olivierlambert** [xapi-project/xen-api#5462]
Currently the `host.cpu_info` record get `cpu_count` and `socket_count` info (among other things). But for many reasons (eg security reasons or even licensing for the environment), we need to know the actual physical core number and/or if SMT is enabled.

Luckily, it should be simple, since we have already the info `thread_per_core` when XAPI populates the `host.cpu_info` field.

For reference, showing we already have the info but it's not just populated: https://github.com/xapi-project/xen-api/blob/master/ocaml/xenopsd/xc/xenops_server_xen.ml#L986

**Comment by edwintorok** [comment]
you can indirectly discover this through the presence of the `ht` flag (although that wouldn't let you differentiate between a theoretical 2 or 4 threads per core).
More topology info in Host would definitely be useful, e.g. we could also expose NUMA node count (which can be different than socket count).

**Comment by olivierlambert** [comment]
@benjamreis will provide a PR next week to expose the thread per core thing, I wanted to assign him but I can't. Maybe it would be nice to have someone at Vates with a bit more permissions to do those things without having to wait for someone else to do so :)

**Comment by benjamreis** [comment]
@olivierlambert I think this can be close, the PR has been merged. :)

**Comment by olivierlambert** [comment]
:+1:
