### ISSUE TITLE
maxmem_kb leak during migration

### ISSUE THREAD

**Issue by amarao** [xapi-project/xen-api#955]
XCP 1.6:

If vm (pv) migrated on localhost, every migration raise maxmem_kb limit for domain.

Steps to reproduce: 
create and start vm (f.e. test).
get an maxmem_kb value for domain from xc.domain_getinfo()
for a in \`seq 1 1000\`;do xe vm-migration vm=test host=\`hostname\`;done
recheck maxmem_kb from xc.domain_getinfo()

Expected: same value
Actual: very large value, raising up after every new migration.

**Comment by simonjbeaumont** [comment]
Looks like there was a pull request to address this issue. I'll close this now.
